#!/usr/bin/env node
// Seeds all 50 hikes for Ben's user account
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

// Load .env.local manually (dotenv doesn't work well in ESM without extra setup)
const env = readFileSync('.env.local', 'utf-8')
env.split('\n').forEach(line => {
  const [k, ...v] = line.split('=')
  if (k && v.length) process.env[k.trim()] = v.join('=').trim()
})

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
)

const USER_ID = 'a2bcae76-355c-4771-949f-2a5928b056ff'

const hikes = [
  { book_number: 1,  name: "Horsetooth Falls",                hub: "Fort Collins",               distance_mi: 2.4, difficulty: "moderate",    elevation_gain_ft: 325,  drive_minutes_denver: 75,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Wildflowers, views, waterfall, cave",                               alltrails_url: "https://www.alltrails.com/trail/us/colorado/horsetooth-falls--4" },
  { book_number: 2,  name: "Chautauqua and Bluebell Loop",    hub: "Boulder",                    distance_mi: 1.6, difficulty: "moderate",    elevation_gain_ft: 463,  drive_minutes_denver: 45,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Flowers, cool geology, history",                                    alltrails_url: "https://www.alltrails.com/trail/us/colorado/chautauqua-and-bluebell-trail-loop" },
  { book_number: 3,  name: "Crags Hotel Ruins",               hub: "Eldorado Springs/Boulder",   distance_mi: 3.0, difficulty: "challenging", elevation_gain_ft: 725,  drive_minutes_denver: 35,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "View, geology, historical ruins",                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/crags-hotel-ruins-and-continental-divide-overlook" },
  { book_number: 4,  name: "White Ranch and Sawmill Trail",   hub: "Golden",                     distance_mi: 2.3, difficulty: "moderate",    elevation_gain_ft: 361,  drive_minutes_denver: 40,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Historic sawmill, view",                                            alltrails_url: "https://www.alltrails.com/trail/us/colorado/sawmill-trail-and-belcher-hill-trail-loop" },
  { book_number: 5,  name: "Lair o' the Bear",                hub: "Morrison",                   distance_mi: 2.0, difficulty: "easy",        elevation_gain_ft: 141,  drive_minutes_denver: 35,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Castle and beautiful creek",                                        alltrails_url: "https://www.alltrails.com/trail/us/colorado/bear-creek-trail-to-the-castle" },
  { book_number: 6,  name: "Brother and Sisters Loop",        hub: "Evergreen",                  distance_mi: 3.5, difficulty: "moderate",    elevation_gain_ft: 456,  drive_minutes_denver: 45,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Meadows, forests, views, cool rocks, climbing",                     alltrails_url: "https://www.alltrails.com/trail/us/colorado/the-brother-and-sisters-loop" },
  { book_number: 7,  name: "Mount Falcon",                    hub: "Morrison",                   distance_mi: 2.6, difficulty: "moderate",    elevation_gain_ft: 361,  drive_minutes_denver: 35,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Meadows, forests, castle ruins, lookout tower",                     alltrails_url: "https://www.alltrails.com/trail/us/colorado/castle-meadow-and-tower-trails" },
  { book_number: 8,  name: "Red Rock Canyon",                 hub: "Manitou Springs",            distance_mi: 1.8, difficulty: "easy",        elevation_gain_ft: 282,  drive_minutes_denver: 75,  best_months: ["Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"], highlights: "Red rocks, quarry, lake",                              alltrails_url: "https://www.alltrails.com/trail/us/colorado/red-rock-canyon-open-space-main-loop" },
  { book_number: 9,  name: "Seven Bridges",                   hub: "Colorado Springs",           distance_mi: 3.7, difficulty: "challenging", elevation_gain_ft: 725,  drive_minutes_denver: 75,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Bridges, creek, forest",                                           alltrails_url: "https://www.alltrails.com/trail/us/colorado/seven-bridges-trail" },
  { book_number: 10, name: "Devil's Head",                    hub: "Castle Rock",                distance_mi: 2.8, difficulty: "challenging", elevation_gain_ft: 843,  drive_minutes_denver: 75,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Views, fire tower, meadows",                                        alltrails_url: "https://www.alltrails.com/trail/us/colorado/devils-head-trail" },
  { book_number: 11, name: "Pine Valley Lake",                hub: "Conifer",                    distance_mi: 1.6, difficulty: "easy",        elevation_gain_ft: 36,   drive_minutes_denver: 45,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Lake, fishing, bridges, old railroad tracks",                       alltrails_url: "https://www.alltrails.com/trail/us/colorado/pine-valley-ranch-loop-trail" },
  { book_number: 12, name: "South Rim of Roxborough",         hub: "Roxborough State Park",      distance_mi: 2.1, difficulty: "moderate",    elevation_gain_ft: 466,  drive_minutes_denver: 40,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Wildflowers, geology, birdwatching, views",                         alltrails_url: "https://www.alltrails.com/trail/us/colorado/south-rim-trail--3" },
  { book_number: 13, name: "Eleven Mile State Park",          hub: "Florissant/Colo Springs",    distance_mi: 4.0, difficulty: "moderate",    elevation_gain_ft: 427,  drive_minutes_denver: 90,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Lake, climbing rocks, caves",                                       alltrails_url: "https://www.alltrails.com/trail/us/colorado/eleven-mile-canyon-trail" },
  { book_number: 14, name: "Twin Lakes",                      hub: "Buena Vista",                distance_mi: 4.6, difficulty: "easy",        elevation_gain_ft: 213,  drive_minutes_denver: 120, best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Lake, historical hotel, meadows, aspens",                           alltrails_url: "https://www.alltrails.com/trail/us/colorado/twin-lakes-trail--4" },
  { book_number: 15, name: "Judd Falls",                      hub: "Crested Butte",              distance_mi: 2.4, difficulty: "moderate",    elevation_gain_ft: 486,  drive_minutes_denver: 195, best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Waterfall, views",                                                  alltrails_url: "https://www.alltrails.com/trail/us/colorado/judd-falls-trail" },
  { book_number: 16, name: "Crater Lake",                     hub: "Snowmass Village",           distance_mi: 4.0, difficulty: "challenging", elevation_gain_ft: 705,  drive_minutes_denver: 180, best_months: ["Jun","Jul","Aug","Sep"], highlights: "Glaciers, views",                                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/crater-lake-trail--3" },
  { book_number: 17, name: "Linkins Lake",                    hub: "Aspen",                      distance_mi: 1.2, difficulty: "moderate",    elevation_gain_ft: 495,  drive_minutes_denver: 165, best_months: ["Jul","Aug","Sep"], highlights: "Lake, mountain views, creek",                                       alltrails_url: "https://www.alltrails.com/trail/us/colorado/linkins-lake-trail" },
  { book_number: 18, name: "Rifle Falls",                     hub: "Rifle",                      distance_mi: 0.9, difficulty: "easy",        elevation_gain_ft: 79,   drive_minutes_denver: 195, best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Caves, waterfalls",                                                 alltrails_url: "https://www.alltrails.com/trail/us/colorado/rifle-falls-trail" },
  { book_number: 19, name: "Uranium Mine",                    hub: "Steamboat Springs",          distance_mi: 3.0, difficulty: "challenging", elevation_gain_ft: 600,  drive_minutes_denver: 165, best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Old mine, wildflowers, creek",                                      alltrails_url: "https://www.alltrails.com/trail/us/colorado/uranium-mine-trail" },
  { book_number: 20, name: "Lake Agnes",                      hub: "Steamboat Springs",          distance_mi: 1.2, difficulty: "challenging", elevation_gain_ft: 410,  drive_minutes_denver: 165, best_months: ["Jul","Aug","Sep"], highlights: "Lake, views",                                                       alltrails_url: "https://www.alltrails.com/trail/us/colorado/lake-agnes-trail--2" },
  { book_number: 21, name: "Adams Falls",                     hub: "Grand Lake",                 distance_mi: 1.1, difficulty: "easy",        elevation_gain_ft: 128,  drive_minutes_denver: 90,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Falls, creek fun, meadows",                                         alltrails_url: "https://www.alltrails.com/trail/us/colorado/adams-falls-trail" },
  { book_number: 22, name: "Dream and Emerald Lakes",         hub: "Estes Park",                 distance_mi: 3.4, difficulty: "challenging", elevation_gain_ft: 712,  drive_minutes_denver: 90,  best_months: ["Jun","Jul","Aug","Sep"], highlights: "Three lakes, views, elk",                                           alltrails_url: "https://www.alltrails.com/trail/us/colorado/dream-lake-trail" },
  { book_number: 23, name: "Alberta Falls",                   hub: "Estes Park",                 distance_mi: 1.6, difficulty: "easy",        elevation_gain_ft: 224,  drive_minutes_denver: 90,  best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Falls, cool rocks, views",                                          alltrails_url: "https://www.alltrails.com/trail/us/colorado/alberta-falls-trail" },
  { book_number: 24, name: "Lumpy Ridge",                     hub: "Estes Park",                 distance_mi: 1.9, difficulty: "moderate",    elevation_gain_ft: 433,  drive_minutes_denver: 90,  best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Views, cool rocks",                                                 alltrails_url: "https://www.alltrails.com/trail/us/colorado/lumpy-ridge-loop-trail" },
  { book_number: 25, name: "Mitchell Lake",                   hub: "Ward",                       distance_mi: 1.8, difficulty: "easy",        elevation_gain_ft: 223,  drive_minutes_denver: 75,  best_months: ["Jul","Aug","Sep"], highlights: "Lake",                                                              alltrails_url: "https://www.alltrails.com/trail/us/colorado/mitchell-lake-trail" },
  { book_number: 26, name: "Saint Mary's Glacier",            hub: "Idaho Springs",              distance_mi: 1.8, difficulty: "challenging", elevation_gain_ft: 591,  drive_minutes_denver: 60,  best_months: ["Jun","Jul","Aug","Sep"], highlights: "Glacier, views, lake",                                              alltrails_url: "https://www.alltrails.com/trail/us/colorado/saint-marys-glacier-trail" },
  { book_number: 27, name: "Chief Mountain",                  hub: "Idaho Springs",              distance_mi: 3.2, difficulty: "challenging", elevation_gain_ft: 928,  drive_minutes_denver: 60,  best_months: ["Jun","Jul","Aug","Sep"], highlights: "Summit, views, evergreen forest",                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/chief-mountain-trail--2" },
  { book_number: 28, name: "Lily Pad Lake",                   hub: "Breckenridge",               distance_mi: 3.3, difficulty: "moderate",    elevation_gain_ft: 354,  drive_minutes_denver: 90,  best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Lake, moose",                                                       alltrails_url: "https://www.alltrails.com/trail/us/colorado/lily-pad-lake-trail" },
  { book_number: 29, name: "Lower Cataract Lake",             hub: "Silverthorne",               distance_mi: 2.3, difficulty: "moderate",    elevation_gain_ft: 223,  drive_minutes_denver: 80,  best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Lake, waterfall",                                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/lower-cataract-lake-trail" },
  { book_number: 30, name: "Sallie Barber Mine",              hub: "Breckenridge",               distance_mi: 3.0, difficulty: "challenging", elevation_gain_ft: 394,  drive_minutes_denver: 90,  best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "Old mine",                                                          alltrails_url: "https://www.alltrails.com/trail/us/colorado/sallie-barber-mine-trail" },
  { book_number: 31, name: "Harpers Corner",                  hub: "Dinosaur",                   distance_mi: 2.2, difficulty: "moderate",    elevation_gain_ft: 285,  drive_minutes_denver: 225, best_months: ["Apr","May","Jun","Sep","Oct","Nov"], highlights: "Dinosaur tracks, geology",                                          alltrails_url: "https://www.alltrails.com/trail/us/colorado/harpers-corner-trail" },
  { book_number: 32, name: "Coke Ovens",                      hub: "Grand Junction",             distance_mi: 1.4, difficulty: "easy",        elevation_gain_ft: 141,  drive_minutes_denver: 225, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Desert bighorn sheep, unusual rock formations, great canyon views", alltrails_url: "https://www.alltrails.com/trail/us/colorado/coke-ovens-trail" },
  { book_number: 33, name: "Devil's Kitchen",                 hub: "Grand Junction",             distance_mi: 1.4, difficulty: "moderate",    elevation_gain_ft: 52,   drive_minutes_denver: 225, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "An awesome geologic playground",                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/devils-kitchen-trail" },
  { book_number: 34, name: "Mica Mine",                       hub: "Grand Junction",             distance_mi: 2.6, difficulty: "moderate",    elevation_gain_ft: 291,  drive_minutes_denver: 225, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Rockhounding, hoodoos, old mine equipment",                         alltrails_url: "https://www.alltrails.com/trail/us/colorado/mica-mine-trail" },
  { book_number: 35, name: "Exclamation Point",               hub: "Gunnison/Grand Junction",    distance_mi: 3.0, difficulty: "moderate",    elevation_gain_ft: 384,  drive_minutes_denver: 225, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Crazy canyon views, neat geology",                                  alltrails_url: "https://www.alltrails.com/trail/us/colorado/exclamation-point-trail" },
  { book_number: 36, name: "Dillon Pinnacles",                hub: "Sanpiero/Grand Junction",    distance_mi: 3.7, difficulty: "moderate",    elevation_gain_ft: 489,  drive_minutes_denver: 195, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Volcanic pinnacles, views",                                         alltrails_url: "https://www.alltrails.com/trail/us/colorado/dillon-pinnacles-trail" },
  { book_number: 37, name: "Sand Canyon",                     hub: "Cortez",                     distance_mi: 2.2, difficulty: "easy",        elevation_gain_ft: 315,  drive_minutes_denver: 330, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Cliff dwellings, views, canyons, history, geology",                 alltrails_url: "https://www.alltrails.com/trail/us/colorado/sand-canyon-trail--2" },
  { book_number: 38, name: "Petroglyph Point",                hub: "Cortez",                     distance_mi: 2.4, difficulty: "challenging", elevation_gain_ft: 328,  drive_minutes_denver: 330, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Cliff dwellings, views, canyons, history, geology",                 alltrails_url: "https://www.alltrails.com/trail/us/colorado/petroglyph-point-trail" },
  { book_number: 39, name: "Keystone Gorge",                  hub: "Telluride",                  distance_mi: 1.8, difficulty: "moderate",    elevation_gain_ft: 492,  drive_minutes_denver: 330, best_months: ["Jun","Jul","Aug","Sep","Oct"], highlights: "River, bridges, gorge, views, mining ruins",                        alltrails_url: "https://www.alltrails.com/trail/us/colorado/keystone-gorge-trail" },
  { book_number: 40, name: "Bear Creek Preserve",             hub: "Telluride",                  distance_mi: 4.8, difficulty: "challenging", elevation_gain_ft: 925,  drive_minutes_denver: 330, best_months: ["Jun","Jul","Aug","Sep"], highlights: "Waterfall, river, views",                                           alltrails_url: "https://www.alltrails.com/trail/us/colorado/bear-creek-trail--8" },
  { book_number: 41, name: "Twin Sisters",                    hub: "Durango",                    distance_mi: 2.6, difficulty: "easy",        elevation_gain_ft: 390,  drive_minutes_denver: 330, best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Views, lake, forest",                                              alltrails_url: "https://www.alltrails.com/trail/us/colorado/twin-sisters-trail--7" },
  { book_number: 42, name: "Perimeter and Ice Park Loop",     hub: "Ouray",                      distance_mi: 3.9, difficulty: "challenging", elevation_gain_ft: 1030, drive_minutes_denver: 300, best_months: ["Jun","Jul","Aug","Sep"], highlights: "Water play, creek, river, waterfalls, views, geological features",  alltrails_url: "https://www.alltrails.com/trail/us/colorado/perimeter-trail-and-ice-park-loop" },
  { book_number: 43, name: "Sheep Creek Hot Springs",         hub: "Pagosa Springs",             distance_mi: 3.5, difficulty: "challenging", elevation_gain_ft: 689,  drive_minutes_denver: 270, best_months: ["May","Jun","Jul","Aug","Sep","Oct"], highlights: "Hot springs, river, forest",                                        alltrails_url: "https://www.alltrails.com/trail/us/colorado/sheep-creek-trail" },
  { book_number: 44, name: "Zapata Falls",                    hub: "Alamosa",                    distance_mi: 1.2, difficulty: "easy",        elevation_gain_ft: 215,  drive_minutes_denver: 225, best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Hidden waterfall, creek, views of Great Sand Dunes",              alltrails_url: "https://www.alltrails.com/trail/us/colorado/zapata-falls-trail" },
  { book_number: 45, name: "San Isabel",                      hub: "Rye",                        distance_mi: 2.0, difficulty: "moderate",    elevation_gain_ft: 226,  drive_minutes_denver: 120, best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "River, water play, rocks, meadows",                                 alltrails_url: "https://www.alltrails.com/trail/us/colorado/san-isabel-trail" },
  { book_number: 46, name: "Paint Mines Interpretive Park",   hub: "Calhan",                     distance_mi: 2.5, difficulty: "easy",        elevation_gain_ft: 289,  drive_minutes_denver: 75,  best_months: ["Mar","Apr","May","Jun","Sep","Oct","Nov"], highlights: "Geological formations, hoodoos",                                   alltrails_url: "https://www.alltrails.com/trail/us/colorado/paint-mines-interpretive-park-loop" },
  { book_number: 47, name: "Castlewood Canyon",               hub: "Castle Rock",                distance_mi: 2.0, difficulty: "moderate",    elevation_gain_ft: 200,  drive_minutes_denver: 45,  best_months: ["Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"], highlights: "Canyon, creek, cool rocks",                         alltrails_url: "https://www.alltrails.com/trail/us/colorado/inner-canyon-loop-trail" },
  { book_number: 48, name: "Vogel Canyon",                    hub: "La Junta",                   distance_mi: 1.4, difficulty: "easy",        elevation_gain_ft: 125,  drive_minutes_denver: 165, best_months: ["Mar","Apr","May","Sep","Oct","Nov"], highlights: "Sandstone canyon, Native petroglyphs",                             alltrails_url: "https://www.alltrails.com/trail/us/colorado/vogel-canyon-trail" },
  { book_number: 49, name: "Riverside Trail",                 hub: "Fort Morgan",                distance_mi: 1.8, difficulty: "easy",        elevation_gain_ft: 3,    drive_minutes_denver: 75,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "River, birdwatching",                                               alltrails_url: "https://www.alltrails.com/trail/us/colorado/riverside-trail--46" },
  { book_number: 50, name: "Pawnee Buttes",                   hub: "Fort Collins",               distance_mi: 4.3, difficulty: "moderate",    elevation_gain_ft: 338,  drive_minutes_denver: 90,  best_months: ["Apr","May","Jun","Jul","Aug","Sep","Oct"], highlights: "Views, birdwatching",                                               alltrails_url: "https://www.alltrails.com/trail/us/colorado/pawnee-buttes-trail" },
]

async function seed() {
  const rows = hikes.map(h => ({ ...h, user_id: USER_ID }))
  const { error, count } = await supabase
    .from('hikes_50')
    .upsert(rows, { onConflict: 'user_id,book_number' })
    .select('id', { count: 'exact', head: true })

  if (error) {
    console.error('Error:', error.message)
    process.exit(1)
  }
  console.log(`Seeded ${rows.length} hikes (${count ?? '?'} affected)`)
}

seed()
