export const C = {
  cream:   'var(--color-cream)',
  creamDk: 'var(--color-cream-dk)',
  rust:    'var(--color-rust)',
  rustDk:  'var(--color-rust-dk)',
  teal:    'var(--color-teal)',
  tealDk:  'var(--color-teal-dk)',
  dark:    'var(--color-dark)',
  paper:   'var(--color-paper)',
  sand:    'var(--color-sand)',
  sandLt:  'var(--color-sand-lt)',
  ink60:   'var(--color-ink60)',
  ink40:   'var(--color-ink40)',
  ink20:   'var(--color-ink20)',
} as const
